"""Back-compat shim so an existing automations repo written against the
old pip-installable `hapy` library (e.g. home-automations, with `import
hapy`, `import hapy.automations as automations`, `import hapy.helpers as
hapy_helpers`) keeps working completely unchanged against this
integration's runtime — no per-file edits needed to migrate.

Only the small subset of the old `hapy` top-level API actually used by
real automation code is exposed: `hapy.Automation`, the `hapy.automations`
module, and the `hapy.helpers` module. These are the *same* module/class
objects used internally by coordinator.py, not copies — so a `devices.X`
generated by runtime/generators/devices.py and an `automations/kitchen.py`
importing `hapy.automations` both bind against one single
AutomationHandler, EntityHandler, etc. (see the sys.modules-duplication
pitfall noted in runtime/generators/entities.py's dotted-path choice).
"""
import sys
import types

from . import automations as _automations
from . import helpers as _helpers

_MARKER = '_hapy_automation_shim'


def install() -> None:
    existing = sys.modules.get('hapy')
    if existing is not None and getattr(existing, _MARKER, False):
        return

    hapy_shim = types.ModuleType('hapy')
    setattr(hapy_shim, _MARKER, True)
    hapy_shim.Automation = _automations.Automation
    hapy_shim.automations = _automations
    hapy_shim.helpers = _helpers

    sys.modules['hapy'] = hapy_shim
    sys.modules['hapy.automations'] = _automations
    sys.modules['hapy.helpers'] = _helpers
